<a href="https://colab.research.google.com/github/suryadwd/PYTORCH/blob/main/pytorch_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("learning pytorch")


learning pytorch


In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [4]:
print(torch.cuda.is_available())

False


LEARNING TENSORS
**bold text**

Pytorch tensors are created using torch.tensor()

In [5]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [8]:
#n of dimensions are the number of box bracket it have
vector.ndim

1

In [9]:
#the shape of vector
vector.shape

torch.Size([2])

In [10]:
#Matrix
Matrix = torch.tensor([[1,4],[7,9]])
Matrix

tensor([[1, 4],
        [7, 9]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.shape


torch.Size([2, 2])

In [13]:
#Tensor
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.dtype

torch.int64

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

#Random Tensor
#Why random tensors?

Random thensirs are important because the way neural network learn is that th start with tensor full of random numbers and then adjust those numbers to a better represent the data


## stRt with random numbers -> looks at the data -> update random numbers -> look at data -> update random number

In [17]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.3160, 0.8680, 0.9257],
        [0.3043, 0.8937, 0.4282],
        [0.7728, 0.3523, 0.8756]])

In [18]:
random_tensor.ndim


2

In [19]:
random_tensor = torch.rand(1,3,3)
random_tensor

tensor([[[0.2700, 0.2282, 0.6598],
         [0.8855, 0.9749, 0.2868],
         [0.4710, 0.6884, 0.0244]]])

In [20]:
random_tensor.ndim

3

In [21]:
#size is optional
random_image_size_tensor = torch.rand(size=(224,224,3)) #height width color
random_image_size_tensor.shape


torch.Size([224, 224, 3])

In [22]:
random_image_size_tensor.ndim

3

In [23]:
#zeros tensor
zeros = torch.zeros(2,2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [24]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
#creating a range of tensors
torch.range(0,5)

<ipython-input-26-e33a50128969>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [27]:
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [28]:
nums = torch.arange(start=0,end=50,step = 10)
nums

tensor([ 0, 10, 20, 30, 40])

In [29]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=nums)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [30]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
#even we define dtype = none but it will not be applicable in it
float_32_tensor.dtype

torch.float32

In [32]:
#we will conver the dtype forcefully now
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [33]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #datatype defines
                               device = None, #what device is your tensor on
                               requires_grad=False) #whether or not track gradients with tensors operator

float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
#they are of differrent datatype but when we perform some operation in it we didint get error sometine
#but this is the not correct thing some time we will get the error
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3,6,9])
int_32_tensor

tensor([3, 6, 9])

In [39]:
int_32_tensor.dtype


torch.int64

In [40]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [41]:
manual_tensor = torch.tensor([1,2,3])
manual_tensor

tensor([1, 2, 3])

In [42]:
auto_tensor = torch.rand(1,3)
auto_tensor

tensor([[0.4807, 0.1878, 0.4844]])

In [43]:
auto_tensor.dtype, auto_tensor.shape, auto_tensor.device

(torch.float32, torch.Size([1, 3]), device(type='cpu'))

In [44]:
manual_tensor.dtype, manual_tensor.shape, manual_tensor.device

(torch.int64, torch.Size([3]), device(type='cpu'))

PERFORMING OPERATION

In [45]:
tensor = torch.tensor([1,2,3])
tensor+69

tensor([70, 71, 72])

In [46]:
tensor * 2

tensor([2, 4, 6])

In [47]:
tensor - 2

tensor([-1,  0,  1])

In [48]:
#using the inbuild method to add but both the methods are correct
torch.add(tensor,10)

tensor([11, 12, 13])

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
tensor * 2


tensor([2, 4, 6])

In [51]:
tensor * tensor

tensor([1, 4, 9])

In [52]:
torch.matmul(tensor,tensor)

tensor(14)

while multiplying two matrix or tensors the inner dimenstion must be matching

In [53]:
#Transposing the matrix
#using transpose we can change the shape,size,dimension of the matrix
tensor_a = torch.tensor([[1,2,3],[7,8,9]])
transpose_tensor_a = tensor_a.T
tensor_a

tensor([[1, 2, 3],
        [7, 8, 9]])

In [54]:
transpose_tensor_a

tensor([[1, 7],
        [2, 8],
        [3, 9]])

MIN MAX MEAN SUM (TENSOR AGGREGATION...)


In [55]:
tensor_x = torch.tensor([1,2,3,4,5])
tensor_x


tensor([1, 2, 3, 4, 5])

In [56]:
tensor_x.min()

tensor(1)

In [57]:
tensor_x.max()

tensor(5)

In [58]:
#mean does work only on float and complex not on int64{lond datatype}
tensor_x = tensor_x.type(torch.float32)
tensor_x.mean()

tensor(3.)

we can use torch.mean(tensor_x), torch.max(tensor_x), torch.min(tensor_x)

In [59]:
torch.sum(tensor_x)

tensor(15.)

In [62]:
tensor_a = torch.tensor([50,20,230,23,76])
tensor_a

tensor([ 50,  20, 230,  23,  76])

In [63]:
#find position of minvalue (index)
tensor_a.argmin()

tensor(1)

In [67]:
tensor_a[1]

tensor(20)

In [68]:
tensor_a.argmax()

tensor(2)

In [69]:
tensor_a[2]

tensor(230)

reshaping stacking squeezing and unsqueezing


In [72]:
import torch
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x.shape

torch.Size([9])

In [78]:
tensor_x = torch.tensor([1,2,3,5,6,78])

In [82]:
# reshapecordinate product must be a equal to the no of element
# first no determine the dimension
reshape_x = tensor_x.reshape(2,3)
reshape_x

tensor([[ 1,  2,  3],
        [ 5,  6, 78]])

In [84]:
reshape_x = reshape_x.reshape(2,1,3)
reshape_x


tensor([[[ 1,  2,  3]],

        [[ 5,  6, 78]]])

In [85]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
reshape_x = x.reshape(2,5)
reshape_x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [87]:
y = torch.tensor([1,2,3,4,5,6,7,8,9,10])

In [88]:
reshape_y = y.reshape(2,5)
reshape_y

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [89]:
#this will also create a another 3d tensor because we are adding an extra 1 dimesnion to it
reshape_y = y.reshape(1,2,5)
reshape_y

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])

according to my observation the number of input in the params of reshape is the dimension of the matrix and all the multiples will be equal to the no of elements

In [91]:
x = torch.tensor([1,2,3,4,5,6])
x

tensor([1, 2, 3, 4, 5, 6])

In [93]:
reshape_x = x.reshape(1,2,3)
reshape_x

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [96]:
reshape_x = x.reshape(1,1,6)
reshape_x

tensor([[[1, 2, 3, 4, 5, 6]]])

In [100]:
reshape_x = reshape_x.reshape(-1)
reshape_x

tensor([1, 2, 3, 4, 5, 6])

In [101]:
x = torch.tensor([1,2,3,4,5,6])
z = x.view(1,6)
z

tensor([[1, 2, 3, 4, 5, 6]])

In [105]:
x = torch.tensor([1,2,3,4,5,6])
z = x.view(1,2,3)
z

tensor([[[1, 2, 3],
         [4, 5, 6]]])

stack

In [111]:
x_stack = torch.stack([x,x],dim=0)
x_stack

tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])

squeeze - removes all single dimension