<a href="https://colab.research.google.com/github/suryadwd/PYTORCH/blob/main/pytorch_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("learning pytorch")


learning pytorch


In [1]:
!nvidia-smi


Mon Jan 27 04:27:49 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [3]:
print(torch.cuda.is_available())

True


LEARNING TENSORS
**bold text**

Pytorch tensors are created using torch.tensor()

In [5]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [9]:
#n of dimensions are the number of box bracket it have
vector.ndim

1

In [10]:
#the shape of vector
vector.shape

torch.Size([2])

In [13]:
#Matrix
Matrix = torch.tensor([[1,4],[7,9]])
Matrix

tensor([[1, 4],
        [7, 9]])

In [14]:
Matrix.ndim

2

In [16]:
Matrix.shape


torch.Size([2, 2])

In [17]:
#Tensor
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
Tensor.ndim

3

In [41]:
Tensor.dtype

torch.int64

In [23]:
Tensor.shape

torch.Size([1, 3, 3])

#Random Tensor
#Why random tensors?

Random thensirs are important because the way neural network learn is that th start with tensor full of random numbers and then adjust those numbers to a better represent the data


## stRt with random numbers -> looks at the data -> update random numbers -> look at data -> update random number

In [29]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.5021, 0.3977, 0.1240],
        [0.3239, 0.3766, 0.1539],
        [0.8314, 0.0254, 0.9106]])

In [30]:
random_tensor.ndim


2

In [31]:
random_tensor = torch.rand(1,3,3)
random_tensor

tensor([[[0.8862, 0.3185, 0.6160],
         [0.1426, 0.7211, 0.2317],
         [0.4185, 0.4168, 0.7612]]])

In [32]:
random_tensor.ndim

3

In [37]:
#size is optional
random_image_size_tensor = torch.rand(size=(224,224,3)) #height width color
random_image_size_tensor.shape


torch.Size([224, 224, 3])

In [35]:
random_image_size_tensor.ndim

3

In [39]:
#zeros tensor
zeros = torch.zeros(2,2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [40]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [42]:
ones.dtype

torch.float32

In [43]:
#creating a range of tensors
torch.range(0,5)

<ipython-input-43-1374df59c7dd>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [44]:
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [48]:
nums = torch.arange(start=0,end=50,step = 10)
nums

tensor([ 0, 10, 20, 30, 40])

In [49]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=nums)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [50]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [51]:
#even we define dtype = none but it will not be applicable in it
float_32_tensor.dtype

torch.float32

In [52]:
#we will conver the dtype forcefully now
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [54]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #datatype defines
                               device = None, #what device is your tensor on
                               requires_grad=False) #whether or not track gradients with tensors operator

float_32_tensor

tensor([3., 6., 9.])

In [56]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [57]:
float_32_tensor

tensor([3., 6., 9.])

In [58]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
#they are of differrent datatype but when we perform some operation in it we didint get error sometine
#but this is the not correct thing some time we will get the error
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [60]:
int_32_tensor = torch.tensor([3,6,9])
int_32_tensor

tensor([3, 6, 9])

In [61]:
int_32_tensor.dtype


torch.int64

In [62]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [63]:
manual_tensor = torch.tensor([1,2,3])
manual_tensor

tensor([1, 2, 3])

In [68]:
auto_tensor = torch.rand(1,3)
auto_tensor

tensor([[0.8208, 0.8259, 0.3309]])

In [65]:
auto_tensor.dtype, auto_tensor.shape, auto_tensor.device

(torch.float32, torch.Size([1, 3]), device(type='cpu'))

In [66]:
manual_tensor.dtype, manual_tensor.shape, manual_tensor.device

(torch.int64, torch.Size([3]), device(type='cpu'))

PERFORMING OPERATION

In [69]:
tensor = torch.tensor([1,2,3])
tensor+69

tensor([70, 71, 72])

In [70]:
tensor * 2

tensor([2, 4, 6])

In [71]:
tensor - 2

tensor([-1,  0,  1])

In [72]:
#using the inbuild method to add but both the methods are correct
torch.add(tensor,10)

tensor([11, 12, 13])

In [73]:
tensor

tensor([1, 2, 3])

In [74]:
tensor * 2


tensor([2, 4, 6])

In [75]:
tensor * tensor

tensor([1, 4, 9])

In [78]:
torch.matmul(tensor,tensor)

tensor(14)

while multiplying two matrix or tensors the inner dimenstion must be matching

In [83]:
#Transposing the matrix
#using transpose we can change the shape,size,dimension of the matrix
tensor_a = torch.tensor([[1,2,3],[7,8,9]])
transpose_tensor_a = tensor_a.T
tensor_a

tensor([[1, 2, 3],
        [7, 8, 9]])

In [82]:
transpose_tensor_a

tensor([[1, 7],
        [2, 8],
        [3, 9]])

MIN MAX MEAN SUM (TENSOR AGGREGATION...)


In [85]:
tensor_x = torch.tensor([1,2,3,4,5])
tensor_x


tensor([1, 2, 3, 4, 5])

In [88]:
tensor_x.min()

tensor(1)

In [89]:
tensor_x.max()

tensor(5)

In [93]:
#mean does work only on float and complex not on int64{lond datatype}
tensor_x = tensor_x.type(torch.float32)
tensor_x.mean()

tensor(3.)

we can use torch.mean(tensor_x), torch.max(tensor_x), torch.min(tensor_x)

In [94]:
torch.sum(tensor_x)

tensor(15.)